port: 8080
endpoint: /v1
proxy:
  target: https://map.happyman.idv.tw/rudy
webroot: /webroot
mirrors:
  file: /mirrors.yaml
  default_scheme: "https:"
firestore:
  project_id: "*detect-project-id*"
  collection: RudyMirrors
