files:
  others:
  - extra/Markchoo.map.zip
  - extra/Compartment.map.zip
  - hgtmix.zip
  - hgt90.zip
  - legend_V1R1.pdf
  daily:
  - drops/MOI_OSM_Taiwan_TOPO_Rudy.map.zip
  - drops/MOI_OSM_Taiwan_TOPO_Rudy_style.zip
  - drops/MOI_OSM_Taiwan_TOPO_Rudy_hs_style.zip
  - drops/MOI_OSM_Taiwan_TOPO_Rudy_locus_style.zip
  - drops/MOI_OSM_extra_style.zip
  - drops/MOI_OSM_bn_style.zip
  - drops/MOI_OSM_dn_style.zip
  - drops/Install_MOI_Taiwan_TOPO_camp3D.exe
  - drops/Taiwan_moi_zh_camp3D.gmap.zip
  weekly:
  - carto_all.cpkg
  - carto_upgrade.cpkg
  - carto_dem.cpkg
  - carto_style.cpkg
  - carto_map.cpkg
  - MOI_OSM_Taiwan_TOPO_Rudy.map.zip
  - MOI_OSM_Taiwan_TOPO_Rudy.zip
  - MOI_OSM_Taiwan_TOPO_Rudy_locus.zip
  - MOI_OSM_Taiwan_TOPO_Rudy_hs_style.zip
  - MOI_OSM_Taiwan_TOPO_Lite.zip
  - MOI_OSM_Taiwan_TOPO_Lite.map.zip
  - MOI_OSM_Taiwan_TOPO_Lite_style.zip
  - MOI_OSM_Taiwan_TOPO_Rudy.poi.zip
  - MOI_OSM_Taiwan_TOPO_Rudy_style.zip
  - MOI_OSM_twmap_style.zip
  - MOI_OSM_Taiwan_TOPO_Rudy_locus_style.zip
  - MOI_OSM_extra_style.zip
  - MOI_OSM_bn_style.zip
  - MOI_OSM_dn_style.zip
  - MOI_OSM_tn_style.zip
  - gmapsupp_Taiwan_moi_en_bw.img.zip
  - gmapsupp_Taiwan_moi_zh_bw.img.zip
  - gmapsupp_Taiwan_moi_zh_bw3D.img.zip
  - gmapsupp_Taiwan_moi_zh_odc.img.zip
  - gmapsupp_Taiwan_moi_zh_odc3D.img.zip
  - gmapsupp_Taiwan_moi_zh_camp3D.img.zip
  - Install_MOI_Taiwan_TOPO_odc3D.exe
  - Install_MOI_Taiwan_TOPO_camp.exe
  - Install_MOI_Taiwan_TOPO_camp3D_en.exe
  - Install_MOI_Taiwan_TOPO_camp3D.exe
  - Taiwan_moi_en_camp3D.gmap.zip
  - Taiwan_moi_zh_odc3D.gmap.zip
  - Taiwan_moi_zh_camp.gmap.zip
  - Taiwan_moi_zh_camp3D.gmap.zip
sites:
- name: Rex
  scheme: https
  host: rudy.basecamp.tw
  weight: 0
- name: KC Wu
  scheme: https
  host: moi.kcwu.csie.org
  landing: taiwan_topo.html
  weight: 4
- name: Happyman
  scheme: https
  host: map.happyman.idv.tw
  prefix: /rudy
  weight: 1
- name: OSL
  statuspage: Outdoor Safety Lab
  firestore: Map Manager
  scheme: https
  host: d3r5lsn28erp7o.cloudfront.net
  weight: 2
  hidden: false
apps:
- id: gts
  name: 綠野遊蹤
  icon: /images/GTS.png
  description: |
    <p>綠野遊蹤支援 Android 平台。若您還沒在手機上安裝，請到至 <a href="https://play.google.com/store/apps/details?id=com.mountain.tracks">Play Store</a> 進行安裝。</p>
  variants:
  - id: standard
    name: 傳統版
    artifacts:
    - id: all
      name: 三合一
      scheme: 'gts-all:'
      file: MOI_OSM_Taiwan_TOPO_Rudy.zip
    - id: map
      name: 離線地圖
      scheme: 'gts-map:'
      file: MOI_OSM_Taiwan_TOPO_Rudy.map.zip
    - id: style
      name: 風格主題
      scheme: 'gts-mapthemes:'
      file: MOI_OSM_Taiwan_TOPO_Rudy_hs_style.zip
    - id: hgt
      name: 高程檔
      scheme: 'gts-hgt:'
      file: hgtmix.zip
  - id: lite
    name: 輕量版
    artifacts:
    - id: all
      name: 三合一
      scheme: 'gts-all:'
      file: MOI_OSM_Taiwan_TOPO_Lite.zip
    - id: map
      name: 離線地圖
      scheme: 'gts-map:'
      file: MOI_OSM_Taiwan_TOPO_Lite.map.zip
    - id: style
      name: 風格主題
      scheme: 'gts-mapthemes:'
      file: MOI_OSM_Taiwan_TOPO_Lite_style.zip
    - id: hgt
      name: 高程檔
      scheme: 'gts-hgt:'
      file: hgt90.zip
- id: oruxmaps
  name: OruxMaps
  description: |
    <p>OruxMaps 支援 Android 平台。若您還沒在手機上安裝，請先到 <a href="https://play.google.com/store/apps/details?id=com.orux.oruxmapsDonate">Play Store</a> 安裝贊助版，或至其<a href="https://www.oruxmaps.com/cs/en/more/downloads">官網</a>安裝免費版。</p>
  icon: /images/OruxMaps.jpeg
  variants:
  - id: standard
    name: 傳統版
    artifacts:
    - id: map
      name: 離線地圖
      icon: /images/OruxMaps_map.jpeg
      scheme: "orux-map:"
      file: MOI_OSM_Taiwan_TOPO_Rudy.map.zip
    - id: style
      name: 風格主題
      icon: /images/OruxMaps_style.jpeg
      scheme: "orux-mf-theme:"
      file: MOI_OSM_Taiwan_TOPO_Rudy_style.zip
    - id: hgt
      name: 高程檔
      icon: /images/OruxMaps_dem.jpeg
      file: hgtmix.zip
  - id: lite
    name: 輕量版
    artifacts:
    - id: map
      name: 離線地圖
      icon: /images/OruxMaps_map.jpeg
      scheme: "orux-map:"
      file: MOI_OSM_Taiwan_TOPO_Lite.map.zip
    - id: style
      name: 風格主題
      icon: /images/OruxMaps_style.jpeg
      scheme: "orux-mf-theme:"
      file: MOI_OSM_Taiwan_TOPO_Lite_style.zip
    - id: hgt
      name: 高程檔
      icon: /images/OruxMaps_dem.jpeg
      file: hgt90.zip
- id: locus
  name: Locus Map
  icon: /images/Locus.jpeg
  description: |
    <p>Locus 支援 Android 平台。若您還沒在手機上安裝，請到至 <a href="https://play.google.com/store/apps/details?id=menion.android.locus">Play Store</a> 安裝。</p>
  variants:
  - id: separate
    name: 分開安裝
    artifacts:
    - id: map
      name: 離線地圖
      icon: /images/Locus_map.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_map-cedric.xml
      file: MOI_OSM_Taiwan_TOPO_Rudy_locus.zip
    - id: style
      name: 風格主題
      icon: /images/Locus_style.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_style-cedric.xml
      file: MOI_OSM_Taiwan_TOPO_Rudy_locus_style.zip
    - id: hgt
      name: 高程檔
      icon: /images/Locus_dem.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_dem-cedric.xml
      file: hgtmix.zip
  - id: together
    name: 合併安裝
    artifacts:
    - id: allinone
      name: 三合一
      icon: /images/Locus.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_all-cedric.xml
    - id: upgrade
      name: 地圖及風格
      icon: /images/Locus.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_upgrade-cedric.xml
- id: carto
  name: Cartograph Pro 2
  icon: /images/Cartograph.png
  description: |
    <p>Cartograph 支援 iPhone (iOS) 及 Android 雙平台。若您還沒在手機上安裝，請到至 <a href="https://play.google.com/store/apps/details?id=eu.cartograph.pro">Play Store 安裝 Android 版</a>，或至<a href="https://apps.apple.com/tw/app/cartograph-2-maps/id1082995961">App Store 安裝 iOS 版</a>。</p>
  variants:
  - id: separate
    name: 分開安裝
    artifacts:
    - id: map
      name: 離線地圖
      icon: /images/Cartograph_map.png
      scheme: "cartograph-map:"
      file: carto_map.cpkg
    - id: style
      name: 風格主題
      icon: /images/Cartograph_style.png
      scheme: "cartograph-map:"
      file: carto_style.cpkg
    - id: hgt
      name: 高程檔
      icon: /images/Cartograph_dem.png
      scheme: "cartograph-map:"
      file: carto_dem.cpkg
  - id: together
    name: 合併安裝
    artifacts:
    - id: allinone
      name: 三合一
      scheme: "cartograph-map:"
      file: carto_all.cpkg
    - id: upgrade
      name: 地圖及風格
      scheme: "cartograph-map:"
      file: carto_upgrade.cpkg
