sites:
- name: Rex
  scheme: https
  host: rudy.basecamp.tw
  weight: 1
- name: KC Wu
  scheme: https
  host: moi.kcwu.csie.org
  weight: 1
- name: Happyman
  scheme: https
  host: map.happyman.idv.tw
  prefix: /rudy
  weight: 1
- name: Map Manager
  scheme: https
  host: d3r5lsn28erp7o.cloudfront.net
  weight: 0
  hidden: true
apps:
- id: gts
  name: 綠野遊蹤
  icon: https://github.com/alpha-rudy/taiwan-topo/raw/master/docs/images/GTS.png
  variants:
  - id: standard
    name: 傳統版
    artifacts:
    - id: all
      name: 三合一
      scheme: 'gts-all:'
      file: MOI_OSM_Taiwan_TOPO_Rudy.zip
    - id: map
      name: 離線地圖
      scheme: 'gts-map:'
      file: MOI_OSM_Taiwan_TOPO_Rudy.map.zip
    - id: style
      name: 風格主題
      scheme: 'gts-mapthemes:'
      file: MOI_OSM_Taiwan_TOPO_Rudy_hs_style.zip
    - id: hgt
      name: 高程檔
      scheme: 'gts-hgt:'
      file: hgtmix.zip
  - id: lite
    name: 輕量版
    artifacts:
    - id: all
      name: 三合一
      scheme: 'gts-all:'
      file: MOI_OSM_Taiwan_TOPO_Lite.zip
    - id: map
      name: 離線地圖
      scheme: 'gts-map:'
      file: MOI_OSM_Taiwan_TOPO_Lite.map.zip
    - id: style
      name: 風格主題
      scheme: 'gts-mapthemes:'
      file: MOI_OSM_Taiwan_TOPO_Lite_style.zip
    - id: hgt
      name: 高程檔
      scheme: 'gts-hgt:'
      file: hgt90.zip
- id: oruxmaps
  name: OruxMaps
  icon: https://github.com/alpha-rudy/taiwan-topo/raw/master/docs/images/OruxMaps.jpeg
  variants:
  - id: default
    artifacts:
    - id: map
      name: 離線地圖
      icon: https://github.com/alpha-rudy/taiwan-topo/raw/master/docs/images/OruxMaps_map.jpeg
      scheme: "orux-map:"
      file: MOI_OSM_Taiwan_TOPO_Rudy.map.zip
    - id: style
      name: 風格主題
      icon: https://github.com/alpha-rudy/taiwan-topo/raw/master/docs/images/OruxMaps_style.jpeg
      scheme: "orux-mf-theme:"
      file: MOI_OSM_Taiwan_TOPO_Rudy_style.zip
    - id: hgt
      name: 高程檔
      icon: https://github.com/alpha-rudy/taiwan-topo/raw/master/docs/images/OruxMaps_dem.jpeg
      file: hgtmix.zip
- id: carto
  name: Cartograph Pro 2
  icon: https://github.com/alpha-rudy/taiwan-topo/raw/master/docs/images/Cartograph.png
  variants:
  - id: default
    name: 分開安裝
    artifacts:
    - id: map
      name: 離線地圖
      icon: https://github.com/alpha-rudy/taiwan-topo/raw/master/docs/images/Cartograph_map.png
      scheme: "cartograph-map:"
      file: carto_map.cpkg
    - id: style
      name: 風格主題
      icon: https://github.com/alpha-rudy/taiwan-topo/raw/master/docs/images/Cartograph_style.png
      scheme: "cartograph-map:"
      file: carto_style.cpkg
    - id: hgt
      name: 高程檔
      icon: https://github.com/alpha-rudy/taiwan-topo/raw/master/docs/images/Cartograph_dem.png
      scheme: "cartograph-map:"
      file: carto_dem.cpkg
  - id: allinone
    name: 三合一
    artifacts:
    - id: install
      name: 首次安裝
      scheme: "cartograph-map:"
      file: carto_all.cpkg
    - id: update
      name: 更新
      scheme: "cartograph-map:"
      file: carto_upgrade.cpkg
