files:
  others:
  - extra/Markchoo.map.zip
  - extra/Compartment.map.zip
  - hgtmix.zip
  - hgt90.zip
  - legend_V1R1.pdf
  - legend_V1R3.pdf
  daily:
  - drops/MOI_OSM_Taiwan_TOPO_Rudy.map.zip
  - drops/MOI_OSM_Taiwan_TOPO_Rudy_style.zip
  - drops/MOI_OSM_Taiwan_TOPO_Rudy_hs_style.zip
  - drops/MOI_OSM_Taiwan_TOPO_Rudy_locus_style.zip
  - drops/MOI_OSM_extra_style.zip
  - drops/MOI_OSM_bn_style.zip
  - drops/MOI_OSM_dn_style.zip
  - drops/Install_MOI_Taiwan_TOPO_camp3D.exe
  - drops/Taiwan_moi_zh_camp3D.gmap.zip
  - drops/hgtmix.zip
  weekly:
  - carto_all.cpkg
  - carto_upgrade.cpkg
  - carto_dem.cpkg
  - carto_style.cpkg
  - carto_map.cpkg
  - MOI_OSM_Taiwan_TOPO_Rudy.map.zip
  - MOI_OSM_Taiwan_TOPO_Rudy.zip
  - MOI_OSM_Taiwan_TOPO_Rudy_locus.zip
  - MOI_OSM_Taiwan_TOPO_Rudy_hs_style.zip
  - MOI_OSM_Taiwan_TOPO_Lite.zip
  - MOI_OSM_Taiwan_TOPO_Lite.map.zip
  - MOI_OSM_Taiwan_TOPO_Lite_style.zip
  - MOI_OSM_Taiwan_TOPO_Rudy.poi.zip
  - MOI_OSM_Taiwan_TOPO_Rudy_style.zip
  - MOI_OSM_twmap_style.zip
  - MOI_OSM_Taiwan_TOPO_Rudy_locus_style.zip
  - MOI_OSM_extra_style.zip
  - MOI_OSM_bn_style.zip
  - MOI_OSM_dn_style.zip
  - MOI_OSM_tn_style.zip
  - gmapsupp_Taiwan_moi_en_bw.img.zip
  - gmapsupp_Taiwan_moi_zh_bw.img.zip
  - gmapsupp_Taiwan_moi_zh_bw3D.img.zip
  - gmapsupp_Taiwan_moi_zh_odc.img.zip
  - gmapsupp_Taiwan_moi_zh_odc3D.img.zip
  - gmapsupp_Taiwan_moi_zh_camp3D.img.zip
  - Install_MOI_Taiwan_TOPO_odc3D.exe
  - Install_MOI_Taiwan_TOPO_camp.exe
  - Install_MOI_Taiwan_TOPO_camp3D_en.exe
  - Install_MOI_Taiwan_TOPO_camp3D.exe
  - Taiwan_moi_en_camp3D.gmap.zip
  - Taiwan_moi_zh_odc3D.gmap.zip
  - Taiwan_moi_zh_camp.gmap.zip
  - Taiwan_moi_zh_camp3D.gmap.zip
sites:
- name: Rex
  host: rudy.basecamp.tw
  redirectscheme: https
  weight: 6
- name: kcwu
  statuspage: KC Wu
  firestore: KC Wu
  host: moi.kcwu.csie.org
  redirectscheme: https
  weight: 4
  proxyscheme: http
  landing: taiwan_topo.html
- name: Happyman
  host: map.happyman.idv.tw
  prefix: /rudy
  redirectscheme: https
  weight: 1
  proxyscheme: http
- name: OSL
  statuspage: Outdoor Safety Lab
  firestore: Outdoor Safety Lab
  host: d3r5lsn28erp7o.cloudfront.net
  redirectscheme: https
  weight: 2
  monthlyQuota: 900000000000 # 1TB*0.9
  proxyscheme: https
apps:
- id: hikinglogger
  name: 山林日誌
  iOS: true
  icon: /images/hj.png
  description: |
    <p>山林日誌支援 iPhone (iOS) 平台，直接在應用程式內下載或更新魯地圖即可。若您還沒在手機上安裝，請至 <a href="https://apps.apple.com/tw/app/hiking-logger/id1450064785">App Store</a> 進行安裝。</p>
- id: wadi
  name: 蛙弟
  android: true
  icon: /images/wadi.png
  description: |
    <p>蛙弟支援 Android 平台，直接在應用程式內下載或更新魯地圖即可。若您還沒在手機上安裝，請至 <a href="https://play.google.com/store/apps/details?id=tw.div.balawu.wadi">Google Play</a> 進行安裝。</p>
- id: gts
  name: 綠野遊蹤
  android: true
  icon: /images/GTS.png
  description: |
    <p>綠野遊蹤支援 Android 平台，可直接在應用程式內下載或更新魯地圖，也支援透過外部更新。若您還沒在手機上安裝，請至 <a href="https://play.google.com/store/apps/details?id=com.mountain.tracks">Google Play</a> 進行安裝。</p>
  variants:
  - id: standard
    name: 傳統版 (10公尺等高線)
    description: 檔案較大，適合較常走高山、中級山或經常使用離線地圖的山友。
    artifacts:
    - id: all
      name: 三合一
      description: <p>同時安裝地圖、風格及高程。</p>
      scheme: 'gts-all:'
      file: MOI_OSM_Taiwan_TOPO_Rudy.zip
    - id: map
      name: 離線地圖
      description: <p>單獨安裝地圖。</p>
      scheme: 'gts-map:'
      file: MOI_OSM_Taiwan_TOPO_Rudy.map.zip
    - id: style
      name: 風格主題
      description: <p>單獨安裝風格主題。</p>
      scheme: 'gts-mapthemes:'
      file: MOI_OSM_Taiwan_TOPO_Rudy_hs_style.zip
    - id: hgt
      name: 高程檔
      description: <p>單獨安裝高程檔。</p>
      scheme: 'gts-hgt:'
      file: hgtmix.zip
  - id: lite
    name: 輕量版 (20公尺等高線)
    description: 檔案較小，適合較常走郊山路線或不常使用離線地圖的山友。
    artifacts:
    - id: all
      name: 三合一
      description: <p>同時安裝輕量版地圖、風格及高程。</p>
      scheme: 'gts-all:'
      file: MOI_OSM_Taiwan_TOPO_Lite.zip
    - id: map
      name: 離線地圖
      description: <p>單獨輕量版安裝地圖。</p>
      scheme: 'gts-map:'
      file: MOI_OSM_Taiwan_TOPO_Lite.map.zip
    - id: style
      name: 風格主題
      description: <p>單獨安裝輕量版風格主題。</p>
      scheme: 'gts-mapthemes:'
      file: MOI_OSM_Taiwan_TOPO_Lite_style.zip
    - id: hgt
      name: 高程檔
      description: <p>單獨安裝輕量版高程檔。</p>
      scheme: 'gts-hgt:'
      file: hgt90.zip
- id: oruxmaps
  name: OruxMaps
  android: true
  description: |
    <p>OruxMaps 支援 Android 平台。若您還沒在手機上安裝，請先到 <a href="https://play.google.com/store/apps/details?id=com.orux.oruxmapsDonate">Google Play</a> 安裝贊助版，或至其<a href="https://www.oruxmaps.com/cs/en/more/downloads">官網</a>安裝免費版。</p>
  icon: /images/OruxMaps.jpeg
  variants:
  - id: standard
    name: 傳統版 (10公尺等高線)
    description: 檔案較大，適合較常走高山、中級山或經常使用離線地圖的山友。
    artifacts:
    - id: map
      name: 離線地圖
      description: <p>圖資下載需要一點時間，請至狀態列確認進度，完成後也請務必切換地圖。</p>
      icon: /images/OruxMaps_map.jpeg
      scheme: "orux-map:"
      file: MOI_OSM_Taiwan_TOPO_Rudy.map.zip
    - id: style
      name: 風格主題
      description: <p>安裝後請切換地圖風格為 MOI_OSM。</p>
      icon: /images/OruxMaps_style.jpeg
      scheme: "orux-mf-theme:"
      file: MOI_OSM_Taiwan_TOPO_Rudy_hs_style.zip
    - id: hgt
      name: 高程檔
      description: <p>OruxMaps 不支援自動安裝，下載後需要自行解壓縮至正確位置。</p>
      icon: /images/OruxMaps_dem.jpeg
      file: hgtmix.zip
  - id: lite
    name: 輕量版 (20公尺等高線)
    description: 檔案較小，適合較常走郊山路線或不常使用離線地圖的山友。
    artifacts:
    - id: map
      name: 離線地圖
      description: <p>圖資下載需要一點時間，請至狀態列確認進度，完成後也請務必切換地圖。</p>
      icon: /images/OruxMaps_map.jpeg
      scheme: "orux-map:"
      file: MOI_OSM_Taiwan_TOPO_Lite.map.zip
    - id: style
      name: 風格主題
      description: <p>安裝後請切換地圖風格為 MOI_OSM。</p>
      icon: /images/OruxMaps_style.jpeg
      scheme: "orux-mf-theme:"
      file: MOI_OSM_Taiwan_TOPO_Lite_style.zip
    - id: hgt
      name: 高程檔
      description: <p>OruxMaps 不支援自動安裝，下載後需要自行解壓縮至正確位置。</p>
      icon: /images/OruxMaps_dem.jpeg
      file: hgt90.zip
- id: locus
  name: Locus Map
  android: true
  icon: /images/Locus.jpeg
  description: |
    <p>Locus 支援 Android 平台。若您還沒在手機上安裝，請至 <a href="https://play.google.com/store/apps/details?id=menion.android.locus">Google Play</a> 安裝。</p>
  variants:
  - id: together
    name: 圖資合併安裝
    description: 一鍵安裝地圖、風格或高程。
    artifacts:
    - id: allinone
      name: 三合一
      description: <p>首次安裝時使用，含地圖、風格及高程。</p>
      icon: /images/Locus.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_all-cedric.xml
    - id: upgrade
      name: 地圖及風格
      description: <p>後續更新時使用，高程較少變動故不需太常更新。</p>
      icon: /images/Locus.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_upgrade-cedric.xml
  - id: separate
    name: 圖資個別安裝
    description: 個別安裝地圖、風格及高程。
    artifacts:
    - id: map
      name: 離線地圖
      description: <p>單獨安裝地圖。</p>
      icon: /images/Locus_map.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_map-cedric.xml
      file: MOI_OSM_Taiwan_TOPO_Rudy_locus.zip
    - id: style
      name: 風格主題
      description: <p>單獨安裝風格主題。</p>
      icon: /images/Locus_style.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_style-cedric.xml
      file: MOI_OSM_Taiwan_TOPO_Rudy_locus_style.zip
    - id: hgt
      name: 高程檔
      description: <p>單獨安裝高程檔。</p>
      icon: /images/Locus_dem.jpeg
      url: locus-actions://https/rudy.outdoors.tw/locus_dem-cedric.xml
      file: hgtmix.zip
- id: carto
  name: Cartograph Maps
  android: true
  iOS: true
  icon: /images/Cartograph.png
  description: |
    <p>Cartograph 支援 iPhone (iOS) 及 Android 雙平台。若您還沒在手機上安裝 Cartograph Maps 3，請至 <a href="https://play.google.com/store/apps/details?id=eu.cartograph3">Google Play 安裝 Android 版</a>，或至 <a href="https://apps.apple.com/us/app/cartograph-maps-3/id1588186796">App Store 安裝 iOS 版</a>。</p><p>若您想使用舊版的 Cartograph 2 Maps，請至 <a href="https://play.google.com/store/apps/details?id=eu.cartograph.pro">Google Play 安裝 Android 版</a>，或至 <a href="https://apps.apple.com/tw/app/cartograph-2-maps/id1082995961">App Store 安裝 iOS 版</a>。</p>
  variants:
  - id: together
    name: 圖資合併安裝
    description: 一鍵安裝地圖、風格或高程。
    artifacts:
    - id: allinone
      name: 三合一
      description: <p>首次安裝時使用，含地圖、風格及高程。</p>
      scheme: "cartograph-map:"
      file: carto_all.cpkg
    - id: upgrade
      name: 地圖及風格
      description: <p>後續更新時使用，高程較少變動故不需太常更新。</p>
      scheme: "cartograph-map:"
      file: carto_upgrade.cpkg
  - id: separate
    name: 圖資個別安裝
    description: 個別安裝地圖、風格及高程。
    artifacts:
    - id: map
      name: 離線地圖
      description: <p>單獨安裝地圖。</p>
      icon: /images/Cartograph_map.png
      scheme: "cartograph-map:"
      file: carto_map.cpkg
    - id: style
      name: 風格主題
      description: <p>單獨安裝風格主題。</p>
      icon: /images/Cartograph_style.png
      scheme: "cartograph-map:"
      file: carto_style.cpkg
    - id: hgt
      name: 高程檔
      description: <p>單獨安裝高程檔。</p>
      icon: /images/Cartograph_dem.png
      scheme: "cartograph-map:"
      file: carto_dem.cpkg
