steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg'
  - 'GIT_HASH=$SHORT_SHA'
  - '--build-arg'
  - 'GIT_TAG=$TAG_NAME'
  - '-t'
  - 'asia.gcr.io/$PROJECT_ID/rudy-balancer'
  - '-f'
  - '.docker/Dockerfile'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - push
  - asia.gcr.io/$PROJECT_ID/rudy-balancer
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - run
  - deploy
  - $_SERVICE_NAME
  - --image=asia.gcr.io/$PROJECT_ID/rudy-balancer
  - --region=$_REGION
  - --platform=managed
